version: "3.9"

services:


  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: enactor
      MYSQL_DATABASE: myDb
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-penactor" ]
      interval: 5s
      timeout: 20s
      retries: 10

  carp-container:
    image: carp:latest
    container_name: carp-container
    networks:
      - my_network
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    command: [ "sh", "-c", "sleep 10 && dockerize -wait tcp://mysql-container:3306 -timeout 60s" ]



networks:
  my_network:
    driver: bridge
